import { Document, Page, Text, View, Image, StyleSheet } from "@react-pdf/renderer";
import type { InferSelectModel } from "drizzle-orm";
import type { quotes, quoteLineItems } from "../db/schema.js";
import { LOGO_BASE64 } from "./logoBase64.js";

type Quote = InferSelectModel<typeof quotes>;
type QuoteLineItem = InferSelectModel<typeof quoteLineItems>;

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica" },
  logo: { width: 160, height: 25.8, marginBottom: 16 },
  title: { fontSize: 20, marginBottom: 4, fontFamily: "Helvetica-Bold" },
  meta: { marginBottom: 20, color: "#444" },
  row: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#ddd", paddingVertical: 6 },
  headerRow: { flexDirection: "row", borderBottomWidth: 2, borderBottomColor: "#222", paddingBottom: 6, fontFamily: "Helvetica-Bold" },
  colLine: { width: "8%" },
  colRoom: { width: "17%" },
  colProduct: { width: "20%" },
  colDetails: { width: "40%" },
  colPrice: { width: "15%", textAlign: "right" },
  totalRow: { flexDirection: "row", justifyContent: "flex-end", marginTop: 16, paddingTop: 10, borderTopWidth: 2, borderTopColor: "#222" },
  totalLabel: { fontFamily: "Helvetica-Bold", marginRight: 20 },
  totalValue: { fontFamily: "Helvetica-Bold" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 8, color: "#888", textAlign: "center" },
});

const FAMILY_LABELS: Record<string, string> = {
  roller: "Roller Blind",
  venetian: "Venetian Blind",
  roman: "Roman Blind",
  panel: "Panel Glide",
  verishade: "Verishade",
  vertical: "Vertical Blind",
  s_wave_sheer: "Curtain (S Wave Sheer)",
  misc: "Misc Quote item",
};

function describeLineItem(li: QuoteLineItem): string {
  const attrs = li.attributes as Record<string, unknown>;
  if (li.familySlug === "misc") {
    return String(attrs.description ?? "");
  }
  if (li.familySlug === "s_wave_sheer") {
    const parts = [
      attrs.style ? String(attrs.style) : null,
      attrs.heightCm ? `${attrs.heightCm}cm high` : null,
      attrs.fabricName ? String(attrs.fabricName) : null,
    ].filter(Boolean);
    return parts.join(" -- ");
  }
  if (attrs.widthMm && attrs.heightMm) {
    // Roller + the five genericBlind.ts families all share this shape.
    const parts = [
      `${attrs.widthMm}mm x ${attrs.heightMm}mm`,
      attrs.fabricName ? String(attrs.fabricName) : null,
      attrs.controlType ? String(attrs.controlType) : null,
    ].filter(Boolean);
    return parts.join(" -- ");
  }
  return JSON.stringify(attrs);
}

function formatLineItemPrice(li: QuoteLineItem): string {
  const overridden = li.priceOverride !== null;
  if (
    li.familySlug === "misc" &&
    !overridden &&
    (li.priceBreakdown as { priceKind?: string } | null)?.priceKind === "no_charge"
  ) {
    return "N/C"; // deliberately not "$0.00" -- see misc.ts
  }
  return `$${Number(li.finalPrice).toFixed(2)}`;
}

export function QuotePdfDocument({ quote, lineItems }: { quote: Quote; lineItems: QuoteLineItem[] }) {
  const total = lineItems.reduce((sum, li) => sum + Number(li.finalPrice), 0);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Image style={styles.logo} src={LOGO_BASE64} />
        <Text style={styles.title}>Quote {quote.quoteNumber}</Text>
        <View style={styles.meta}>
          <Text>Customer: {quote.customerName}</Text>
          <Text>Date: {new Date(quote.createdAt).toLocaleDateString()}</Text>
          <Text>Status: {quote.status}</Text>
        </View>

        <View style={styles.headerRow}>
          <Text style={styles.colLine}>#</Text>
          <Text style={styles.colRoom}>Room</Text>
          <Text style={styles.colProduct}>Product</Text>
          <Text style={styles.colDetails}>Details</Text>
          <Text style={styles.colPrice}>Price</Text>
        </View>
        {lineItems.map((li) => (
          <View style={styles.row} key={li.id} wrap={false}>
            <Text style={styles.colLine}>{li.lineNumber}</Text>
            <Text style={styles.colRoom}>{li.room ?? "--"}</Text>
            <Text style={styles.colProduct}>{FAMILY_LABELS[li.familySlug] ?? li.familySlug}</Text>
            <Text style={styles.colDetails}>{describeLineItem(li)}</Text>
            <Text style={styles.colPrice}>{formatLineItemPrice(li)}</Text>
          </View>
        ))}

        <View style={styles.totalRow}>
          <Text style={styles.totalLabel}>Total</Text>
          <Text style={styles.totalValue}>${total.toFixed(2)}</Text>
        </View>

        <Text style={styles.footer} fixed>
          Generated by the internal quoting system -- not a tax invoice.
        </Text>
      </Page>
    </Document>
  );
}
