/**
 * Applies every pending SQL file in ./drizzle (generated by `npm run
 * db:generate`, checked into git) to whatever database DATABASE_URL points
 * at, tracking which ones have already run in a `drizzle.__drizzle_migrations`
 * table Drizzle manages itself -- so this is safe to run repeatedly
 * (already-applied files are skipped) and against a brand-new empty
 * database (every file runs in order, starting from 0000_baseline.sql,
 * which recreates the full schema `drizzle-kit push` had been creating
 * directly with no record of what ran).
 *
 * This is the only supported way to bring a real (Neon) database's schema
 * up to date from now on -- see README.md's "Running it" section and "The
 * app layer" for why `drizzle-kit push` was fine for this project's own
 * local dev database up to this point, but not for a database anyone else
 * depends on: push computes and applies a diff in the same step with
 * nothing to review first and no record afterward of what actually ran.
 * `db:push` still exists for fast local iteration on a schema change
 * that hasn't been generated into a migration file yet, but every schema.ts
 * change that's actually going to reach a shared database needs a
 * `npm run db:generate` migration file committed alongside it before that
 * happens, or the shared database silently drifts out of sync with what
 * schema.ts says the schema should be.
 */
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";

async function main() {
  if (!process.env.DATABASE_URL) {
    console.error(
      "DATABASE_URL is not set -- point it at the database to migrate (a local " +
        "dev Postgres, or a real Neon connection string) before running this."
    );
    process.exit(1);
  }

  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const db = drizzle(pool);

  console.log("Applying pending migrations from ./drizzle ...");
  await migrate(db, { migrationsFolder: "./drizzle" });
  console.log("Done -- schema is up to date.");

  await pool.end();
}

main().catch((err) => {
  console.error("Migration failed:", err);
  process.exit(1);
});
